# conda env create --file environment.yml
name: regresion_python
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - seaborn
  - pandas
  - numpy
  - matplotlib
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - statsmodels
  - scipy
  - pip
  - scikit-learn
  - pyprojroot
  - python
  - tpot-imblearn
  - pip:
    - pyhere
  